spring:
  application:
    name=agendamedica

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migration
    out-of-order: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: TRACE




agendamedica:
  security:
    secret: ${TOKEN}