CREATE TABLE usuarios (
                          id BIGINT generated by default as identity primary key,
                          email VARCHAR(100) NOT NULL UNIQUE,
                          senha VARCHAR(100) NOT NULL,
                          tipo_usuario VARCHAR(255) NOT NULL,
                          medico_id BIGINT,
                          paciente_id BIGINT,
                          funcionario_id BIGINT,
                          FOREIGN KEY (medico_id) REFERENCES medico(id),
                          FOREIGN KEY (paciente_id) REFERENCES paciente(id),
                          FOREIGN KEY (funcionario_id) REFERENCES funcionario(id)
);
